version: '3'

services:

  mi-mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=tienda

  tienda_back_end:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mi-mariadb
    command: bash -c "until nc -z mi-mariadb 3306; do sleep 1; done && npm start"
    environment:
      - DB_HOST=mi-mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=tienda

  tienda_front_end:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on: 
      - tienda_back_end
